<?php

namespace tests;

use kat\MailjetMailer;
use Snipworks\Smtp\Email;
use PHPUnit\Framework\TestCase;

class MailJetTest extends TestCase
{


    private string $mailReceiver = 'katlassi_ext@coyote-group.com';
    private string $mailSubject = '*Testcase: Send an email';
    private string $mailContent = <<<END
Hi,
this is a Testcase mail.
Testcase: Send an email
END;
    private MailjetMailer $mailjetMailer;

    private string $mailJetKey = 'd1fb14486042d8930df841144c825dbd';
    private string $mailJetSecret = 'b2082804b1249110f71d9e708e5a7561';
    private ?Client $client = null;
    private $fileNamePath = 'README.md';
    private $downloadableFileName = 'afile.txt';


    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->mailjetMailer = new MailjetMailer();
        $this->mailjetMailer = $this->mailjetMailer
            ->setMailjetKey($this->mailJetKey)
            ->setMailjetSecret($this->mailJetSecret)
            ->setEmailSender($this->mailReceiver)
            ->setEmailReceiver($this->mailReceiver)
            ->setMailSubject($this->mailSubject);
    }

    public function testEmailSentWithEmptyBody()
    {
        $isSent = $this->mailjetMailer
            ->setMailBody('')
            ->send();

        $this->assertTrue($isSent);
    }

    public function testEmailSent()
    {
        $isSent = $this->mailjetMailer
            ->setMailBody('<pre>' . $this->mailContent . '</pre>')
            ->send();

        $this->assertTrue($isSent);
    }


    /**
     * @throws \Exception
     */
    public function testEmailSentWithFile()
    {
        $isSent = $this->mailjetMailer
            ->setEmailSender($this->mailReceiver)
            ->setEmailReceiver($this->mailReceiver)
            ->setMailSubject($this->mailSubject . " - With file!")
            ->setMailBody($this->mailContent . " \nWith file!")
            ->setAttachements(json_decode('[{"ContentType":"text/plain","Filename":"' . $this->downloadableFileName . '","Base64Content":"' . base64_encode(file_get_contents($this->fileNamePath)) . '"}]', true))
            ->send();
        $this->assertTrue($isSent);
    }
}